version: '3'
services:
    nginx:
        build: ./nginx/
        container_name: ngix
        ports:
            - "80:80"
        volumes:
            - "./html/:/var/www/html/"
        restart: always
    php:
        image: php:7.0-fpm
        container_name: php
        volumes:
            - "./html/:/var/www/html/"
        restart: always
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
