version: '3'
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - "./html/:/var/www/html/"
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        restart: always
        depends_on:
            - mysqldb
    php:
        build: ./php
        container_name: php
        volumes:
            - "./html/:/var/www/html/"
        restart: always
        depends_on:
            - mysqldb
    phpmyadmin:
        container_name: xops-phpmyadmin
        restart: always
        image: phpmyadmin/phpmyadmin
        depends_on:
            - mysqldb
    environment:
        - PMA_USER=${MYSQL_USER}
        - PMA_PASSWORD=${MYSQL_PASSWORD}
        - PMA_DB=${MYSQL_DB}
    mysqldb:
        image: mysql:latest
        container_name: mysqldb
        ports:
            - "3306:3306"
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
