version: '3'
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - "./html/:/var/www/html/"
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        restart: always
        depends_on:
            - mysqldb
        networks:
            - XXX
        environment:
            - WORDPRESS_DB_HOST: mysqldb
            - WORDPRESS_DB_USER: ${MYSQL_USER}
            - WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
            - WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    php:
        build: ./php
        container_name: php
        volumes:
            - "./html/:/var/www/html/"
        restart: always
        depends_on:
            - mysqldb
        networks:
            - XXX        
    mysqldb:
        image: mysql:latest
        container_name: mysqldb
        ports:
            - "3306:3306"
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        networks:
            - XXX
networks:
    XXX:
        driver: bridge
        ipam:
            config:
                - subnet: 10.10.1.0/24
