version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./html:/var/www/html"
        restart: always
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
